In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import matplotlib.pyplot as plt

In [4]:
ab=pd.read_csv("C:/Users/HP/OneDrive/Documents/sales_data.csv")

In [5]:
ab.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200
4     1023  2026-01-02      Tablet  Electronics         4        450

In [6]:
ab.tail()

    OrderID        Date     Product     Category  Quantity  UnitPrice
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

In [7]:
ab.columns.tolist()

['OrderID', 'Date', 'Product', 'Category', 'Quantity', 'UnitPrice']

In [8]:
ab.shape

(100, 6)

In [9]:
ab.info

<bound method DataFrame.info of     OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]>

In [10]:
ab.describe()

           OrderID    Quantity    UnitPrice
count   100.000000  100.000000   100.000000
mean   1050.500000    2.660000   577.000000
std      29.011492    1.139023   412.213782
min    1001.000000    1.000000   150.000000
25%    1025.750000    2.000000   250.000000
50%    1050.500000    3.000000   450.000000
75%    1075.250000    4.000000   900.000000
max    1100.000000    4.000000  1200.000000

In [11]:
!pip install loc[]

Requirement already satisfied: loc in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.0.2)
Requirement already satisfied: bidict in .\AppData\Local\Programs\Python\Python314\Lib\site-packages (from loc) (0.24.1)

In [12]:
ab["Product"]

0     Smartphone
1     Headphones
2         Laptop
3         Laptop
4         Tablet
         ...
95        Tablet
96    Headphones
97    Smartwatch
98    Smartwatch
99        Tablet
Name: Product, Length: 100, dtype: str

In [13]:
ab[["Product","Category"]]

       Product     Category
0   Smartphone  Electronics
1   Headphones  Accessories
2       Laptop  Electronics
3       Laptop  Electronics
4       Tablet  Electronics
..         ...          ...
95      Tablet  Electronics
96  Headphones  Accessories
97  Smartwatch  Accessories
98  Smartwatch  Accessories
99      Tablet  Electronics

[100 rows x 2 columns]

In [14]:
ab.iloc[0]

OrderID             1031
Date          2026-01-01
Product       Smartphone
Category     Electronics
Quantity               3
UnitPrice            800
Name: 0, dtype: object

In [15]:
ab.iloc[0:4]

   OrderID        Date     Product     Category  Quantity  UnitPrice
0     1031  2026-01-01  Smartphone  Electronics         3        800
1     1100  2026-01-02  Headphones  Accessories         2        150
2     1028  2026-01-02      Laptop  Electronics         2       1200
3     1089  2026-01-02      Laptop  Electronics         3       1200

In [16]:
ab.loc[0,"Category"]

'Electronics'

In [17]:
ab.loc[1,"Date"]

'2026-01-02'

In [18]:
ab.loc[[1],["Product","Quantity"]]

      Product  Quantity
1  Headphones         2

In [19]:
ab.loc[[1],["Product","Quantity","UnitPrice"]]

      Product  Quantity  UnitPrice
1  Headphones         2        150

In [20]:
ab.loc[[1],["Product","Quantity","UnitPrice","Date"]]

      Product  Quantity  UnitPrice        Date
1  Headphones         2        150  2026-01-02

In [21]:
ab[ab["Quantity"] < 1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [22]:
ab[ab["UnitPrice"]<1000]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
6      1055  2026-01-03  Headphones  Accessories         1        150
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[75 rows x 6 columns]

In [23]:
ab[(ab["Quantity"]>1) & (ab["UnitPrice"]>1000)]

    OrderID        Date Product     Category  Quantity  UnitPrice
2      1028  2026-01-02  Laptop  Electronics         2       1200
3      1089  2026-01-02  Laptop  Electronics         3       1200
18     1058  2026-01-07  Laptop  Electronics         2       1200
23     1018  2026-01-08  Laptop  Electronics         2       1200
24     1087  2026-01-08  Laptop  Electronics         4       1200
36     1025  2026-01-12  Laptop  Electronics         3       1200
42     1048  2026-01-15  Laptop  Electronics         3       1200
43     1004  2026-01-15  Laptop  Electronics         2       1200
46     1044  2026-01-16  Laptop  Electronics         4       1200
47     1038  2026-01-17  Laptop  Electronics         2       1200
48     1084  2026-01-17  Laptop  Electronics         4       1200
51     1097  2026-01-18  Laptop  Electronics         2       1200
69     1052  2026-01-23  Laptop  Electronics         3       1200
71     1015  2026-01-24  Laptop  Electronics         4       1200
73     1019  2026-01-24  Laptop  Electronics         3       1200
78     1033  2026-01-26  Laptop  Electronics         4       1200
87     1074  2026-01-28  Laptop  Electronics         3       1200

In [24]:
ab[ab["Category"].isin(["Electronics","Accessories"])]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
1      1100  2026-01-02  Headphones  Accessories         2        150
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
95     1026  2026-01-30      Tablet  Electronics         1        450
96     1090  2026-01-30  Headphones  Accessories         2        150
97     1049  2026-01-30  Smartwatch  Accessories         4        250
98     1046  2026-01-30  Smartwatch  Accessories         4        250
99     1047  2026-01-30      Tablet  Electronics         3        450

[100 rows x 6 columns]

In [25]:
ab[ab["Category"] == "Electronics"]

    OrderID        Date     Product     Category  Quantity  UnitPrice
0      1031  2026-01-01  Smartphone  Electronics         3        800
2      1028  2026-01-02      Laptop  Electronics         2       1200
3      1089  2026-01-02      Laptop  Electronics         3       1200
4      1023  2026-01-02      Tablet  Electronics         4        450
5      1072  2026-01-02  Smartphone  Electronics         4        800
7      1020  2026-01-03      Laptop  Electronics         1       1200
8      1082  2026-01-03  Smartphone  Electronics         4        800
9      1085  2026-01-04      Laptop  Electronics         1       1200
10     1088  2026-01-04      Tablet  Electronics         4        450
11     1094  2026-01-04      Tablet  Electronics         4        450
16     1027  2026-01-06      Tablet  Electronics         2        450
18     1058  2026-01-07      Laptop  Electronics         2       1200
20     1001  2026-01-07  Smartphone  Electronics         4        800
21     1009  2026-01-07  Smartphone  Electronics         4        800
23     1018  2026-01-08      Laptop  Electronics         2       1200
24     1087  2026-01-08      Laptop  Electronics         4       1200
27     1069  2026-01-09      Tablet  Electronics         4        450
28     1093  2026-01-10      Tablet  Electronics         3        450
34     1051  2026-01-12      Tablet  Electronics         1        450
35     1032  2026-01-12  Smartphone  Electronics         1        800
36     1025  2026-01-12      Laptop  Electronics         3       1200
37     1099  2026-01-12  Smartphone  Electronics         3        800
41     1081  2026-01-15      Tablet  Electronics         4        450
42     1048  2026-01-15      Laptop  Electronics         3       1200
43     1004  2026-01-15      Laptop  Electronics         2       1200
44     1045  2026-01-15      Tablet  Electronics         3        450
46     1044  2026-01-16      Laptop  Electronics         4       1200
47     1038  2026-01-17      Laptop  Electronics         2       1200
48     1084  2026-01-17      Laptop  Electronics         4       1200
50     1086  2026-01-18      Laptop  Electronics         1       1200
51     1097  2026-01-18      Laptop  Electronics         2       1200
53     1057  2026-01-19      Tablet  Electronics         2        450
55     1050  2026-01-19  Smartphone  Electronics         3        800
56     1053  2026-01-20  Smartphone  Electronics         2        800
62     1071  2026-01-21  Smartphone  Electronics         3        800
66     1021  2026-01-22      Laptop  Electronics         1       1200
67     1095  2026-01-22      Laptop  Electronics         1       1200
68     1092  2026-01-22      Laptop  Electronics         1       1200
69     1052  2026-01-23      Laptop  Electronics         3       1200
71     1015  2026-01-24      Laptop  Electronics         4       1200
72     1024  2026-01-24      Tablet  Electronics         1        450
73     1019  2026-01-24      Laptop  Electronics         3       1200
74     1054  2026-01-25  Smartphone  Electronics         4        800
75     1037  2026-01-25  Smartphone  Electronics         2        800
76     1064  2026-01-25      Tablet  Electronics         1        450
78     1033  2026-01-26      Laptop  Electronics         4       1200
79     1068  2026-01-26      Tablet  Electronics         2        450
80     1098  2026-01-26      Tablet  Electronics         3        450
81     1010  2026-01-26      Laptop  Electronics         1       1200
83     1040  2026-01-27      Tablet  Electronics         4        450
84     1029  2026-01-28      Tablet  Electronics         4        450
87     1074  2026-01-28      Laptop  Electronics         3       1200
88     1042  2026-01-28      Tablet  Electronics         4        450
89     1043  2026-01-28      Tablet  Electronics         2        450
93     1035  2026-01-29      Laptop  Electronics         1       1200
94     1007  2026-01-29  Smartphone  Electronics         4        800
95     1026  2026-01-30      Tablet  Electronics         1        450
99     1047  2026-01-30      Tablet  Electronics         3        450

In [26]:
ab.loc[ab["UnitPrice"]>100, ["Product","Category"]]

       Product     Category
0   Smartphone  Electronics
1   Headphones  Accessories
2       Laptop  Electronics
3       Laptop  Electronics
4       Tablet  Electronics
..         ...          ...
95      Tablet  Electronics
96  Headphones  Accessories
97  Smartwatch  Accessories
98  Smartwatch  Accessories
99      Tablet  Electronics

[100 rows x 2 columns]

In [27]:
ab.sort_values("Product",ascending=False)

    OrderID        Date     Product     Category  Quantity  UnitPrice
99     1047  2026-01-30      Tablet  Electronics         3        450
16     1027  2026-01-06      Tablet  Electronics         2        450
44     1045  2026-01-15      Tablet  Electronics         3        450
53     1057  2026-01-19      Tablet  Electronics         2        450
41     1081  2026-01-15      Tablet  Electronics         4        450
..      ...         ...         ...          ...       ...        ...
65     1034  2026-01-22  Headphones  Accessories         1        150
33     1036  2026-01-12  Headphones  Accessories         3        150
22     1080  2026-01-08  Headphones  Accessories         3        150
63     1022  2026-01-21  Headphones  Accessories         1        150
57     1002  2026-01-20  Headphones  Accessories         3        150

[100 rows x 6 columns]

In [28]:
ab["Sales"] = ab["Quantity"] * ab["UnitPrice"]
ab.head()

   OrderID        Date     Product     Category  Quantity  UnitPrice  Sales
0     1031  2026-01-01  Smartphone  Electronics         3        800   2400
1     1100  2026-01-02  Headphones  Accessories         2        150    300
2     1028  2026-01-02      Laptop  Electronics         2       1200   2400
3     1089  2026-01-02      Laptop  Electronics         3       1200   3600
4     1023  2026-01-02      Tablet  Electronics         4        450   1800

In [29]:
ab.groupby("Category")["Sales"].sum()

Category
Accessories     22750
Electronics    127600
Name: Sales, dtype: int64

In [30]:
ab.groupby("Category")["Sales"].mean()

Category
Accessories     541.666667
Electronics    2200.000000
Name: Sales, dtype: float64

In [31]:
ab.groupby("Category")["Sales"].min()

Category
Accessories    150
Electronics    450
Name: Sales, dtype: int64

In [32]:
ab.groupby("Category")["Sales"].max()

Category
Accessories    1000
Electronics    4800
Name: Sales, dtype: int64

In [33]:
ab.groupby("Category")["Sales"].count()

Category
Accessories    42
Electronics    58
Name: Sales, dtype: int64

In [34]:
ab.groupby("Category")["Sales"].std()

Category
Accessories     313.889189
Electronics    1227.034651
Name: Sales, dtype: float64

In [36]:
ab.describe()

           OrderID    Quantity    UnitPrice        Sales
count   100.000000  100.000000   100.000000   100.000000
mean   1050.500000    2.660000   577.000000  1503.500000
std      29.011492    1.139023   412.213782  1258.712165
min    1001.000000    1.000000   150.000000   150.000000
25%    1025.750000    2.000000   250.000000   450.000000
50%    1050.500000    3.000000   450.000000  1000.000000
75%    1075.250000    4.000000   900.000000  2400.000000
max    1100.000000    4.000000  1200.000000  4800.000000